- .gitignore
- README.md
- domain/model/__init__.py
- domain/model/mesh_column.py
- domain/model/mesh_results.py
- domain/model/mesh_row.py
- domain/model/metric.py
- generate_client.sh
- generated/README.md
- infrastructure/data_access/grpc/README.md
- infrastructure/data_access/http/api_client.py
- infrastructure/data_access/http/synthetics_repo.py
- main.py
- presentation/matrix.py
- presentation/matrix_view.py
- requirements.txt
- synthetics.openapi.yaml
> Prototype Mesh Test WebApp implementation

- main.py
- presentation/main_view.py
- presentation/matrix_view.py
> Filled cells with colors depending on latency metric in matrix

- .gitignore
- infrastructure/config/config_toml.py
- main.py
- presentation/main_view.py
- presentation/matrix_view.py
> Updated code according to super-linter findings

- config.yaml
- domain/config/thresholds.py
- infrastructure/config/thresholds.py
- main.py
- presentation/matrix_view.py
> Minor updates after reviews & demo

- main.py
- presentation/main_view.py
- presentation/matrix_view.py
> Added dropdown list with callback for choosing main metric

- data/config.yaml
- domain/cached_repo_request_driven.py
- domain/repo.py
- infrastructure/config/config_yaml.py
- infrastructure/data_access/http/synthetics_repo.py
- main.py
> Added configurable timeouts for fetching synthetics data

- .github/workflows/docker.yml
- Dockerfile
Docker image build verification.
KNTK-259
> Added BuildDockerImage to github actions

- Dockerfile
- infrastructure/data_access/http/synthetics_repo.py
- main.py
- presentation/chart_view.py
- presentation/matrix_view.py
> Install GCC in Dockerfile, scale packet_loss to 0-100%, update label to just Distance, display 3 charts on single page

- Dockerfile
- infrastructure/data_access/http/synthetics_repo.py
- main.py
- presentation/chart_view.py
- presentation/index_view.py
- presentation/matrix_view.py
KNTK-255
Display spinner animation during page loading.
NOTE: based on previous PR
> Page load spinner

- presentation/chart_view.py
> Fit 3 charts in page without scrolling, packet_loss always [0..100]%

- data/assets/04_components.css
- data/assets/05_dash-graph.css
- data/assets/06_legend.css
- data/config.yaml
- domain/config/__init__.py
- domain/config/config.py
- domain/config/matrix.py
- infrastructure/config/config_yaml.py
- presentation/matrix_view.py
> UI custom css

- data/assets/04_components.css
- data/assets/05_dash-graph.css
- data/assets/06_legend.css
- data/config.yaml
- domain/config/__init__.py
- domain/config/config.py
- domain/config/matrix.py
- infrastructure/config/config_yaml.py
- presentation/matrix_view.py
KNTK-275
Based on https://github.com/kentik/sla_dashboard_webapp/pull/32
> Fix: matrix cells coloring

- data/assets/04_components.css
- data/assets/05_dash-graph.css
- data/assets/06_legend.css
- data/config.yaml
- domain/config/__init__.py
- domain/config/config.py
- domain/config/matrix.py
- infrastructure/config/config_yaml.py
- main.py
- presentation/matrix_view.py
KNTK-277
Based on https://github.com/kentik/sla_dashboard_webapp/pull/33
> Fix spinner showing only for split second before chart view loads

- Dockerfile
- README.md
- data/config.yaml
- data/gunicorn.conf.py
- domain/config/thresholds.py
- infrastructure/config/thresholds.py
- presentation/matrix_view.py
Renamed threshold: error -> critical
Configured main:run() as default wsgi_app
Based on #33
> Consistent naming

- data/config.yaml
- domain/config/matrix.py
- domain/model/mesh_results.py
- infrastructure/config/config_yaml.py
- main.py
- presentation/chart_view.py
- presentation/matrix_view.py
> Handle connection "no data" situation

- data/assets/01.js
- presentation/matrix_view.py
Made test result timestamp local to the client not to the server
> Moved UTC->localtime conversion to the client

- domain/model/mesh_results.py
- presentation/chart_view.py
- presentation/matrix_view.py
> Review comments to no-data handling

- main.py
- presentation/chart_view.py
- routing.py
Routing related code moved to routing.py
Metric selection now updates the url
> Added routing module, metric selection is now routable

- generate_client.sh
See: https://github.com/kentik/community_sdk_golang/pull/43#discussion_r667137412
Issue: KNTK-283
> Do not change the group of generated files

- .editorconfig
- .github/workflows/build_test.yml
- data/assets/01.js
- data/assets/03_global.css
- data/assets/05_dash-graph.css
- generate_client.sh
Editorconfig allows to keep consistent indentation style
and saves developer's time from IDE configuration
> Add editorconfig

- synthetics.openapi.yaml
Make the api client understand data returned from api server again.
> Updated synthetics client OpenAPI3 spec

- domain/cached_repo_request_driven.py
- domain/model/mesh_results.py
- infrastructure/data_access/http/synthetics_repo.py
- presentation/matrix_view.py
KNTK-302
- handle no test data at all scenario 
- handle update from no data at all -> data available
> Added handling of no data received scenario

- data/assets/03_global.css
- data/assets/05_matrix_tooltip.css
- data/assets/07_matrix_view.css
- data/config.yaml
- domain/config/config.py
- domain/config/defaults.py
- infrastructure/config/config_yaml.py
- presentation/matrix_view.py
- presentation/time_series_view.py
KNTK-338
- Display time series view header from-to-distance in separate rows
- Fix matrix view vertical column names in less compatible browsers
- Matrix cell tooltip show up when cursor anywhere in the cell
- Cell hover tooltip formatted as a table
- Matrix column headers  -> horizontal
- Configurable flag for show measurement values in matrix
- Metric selector and time range on the same row 
- Legend in matrix cell [0, 0]
> Visual improvements

- data/assets/01.js
- data/assets/03_global.css
- main.py
- presentation/index_view.py
- presentation/matrix_view.py
KNTK-272
- checkbox enabling periodical auto-refresh of the page
> Added periodical page auto-refresh checkbox
